### PR TITLE
Introduce atomic file writing to avoid issues like #9

### LINKED ISSUE #9: scores.json becomes malformat when disk is full
I just accidentally fill my disk and crashes `jump`. It writes a partial scores.json file and all subsequent calls ending up with ` ❯ err: unexpected EOF`

### PR DESCRIPTION
**Pull request by gsamokovarov**
We now write the config files a temporary file and when ready, we move
it to the actual file. The move is an atomic operation, so nothing can
happen in between.

This will let us avoid flocking the file for concurrent reads and will
avoid corruptions that may leave the file with broken content if a write
fails.

Closes #9

### CODE REVIEW

**Comment by gsamokovarov** [comment]
@amosbird This should fix the issue with corrupt files during bad writes.

**Comment by amosbird** [comment]
That's great. In fact I was just bitten by this issue earlier today. Thanks!

**Comment by gsamokovarov** [comment]
I have merged it, so you can test it with a `go get github.com/gsamokovarov/jump` install. Will release a new official version soon enough.

Happy holidays! 🎄

**Comment by amosbird** [comment]
Cool, Happy new year!

**Pull request merged**
